### ISSUE TITLE
Saving a sheet that is "Default Journal entry sheet" causes some major issues. 

### ISSUE THREAD

**Issue by Orionox** [ironmonk88/monks-enhanced-journal#181]
It moves the UI that is usually at the top of my screen down to the bottom left and makes ity unusable doesn't actually save the changes and forces a reload. the only way to fix these issues is to reset foundry.

After a little testing it appears to happen when a sheet is anything other than the enhanced journal version of a sheett.

**Comment by mouse0270** [comment]
I am just adding a note here so when this issue gets closed I'll now. As this is breaking my setup! thanks for fixing it cant wait for the release.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.

**Comment by mouse0270** [comment]
> Should be fixed in the latest release.

Then maybe I am getting a new issue? I am on version 1.0.44 and foundry says I am current, but when I create a new journal entry, then type in the title and hit enter, I lose my sidebar completely causing me to have to exit foundry completely. Only happens with your module enabled, if I disable this module, the issue doesn't happen.

**Comment by Orionox** [comment]
It was happening to me anytime I used a non-enhanced journal sheet for a journal entry. Maybe that's the problem you're running into.

**Comment by mouse0270** [comment]
> It was happening to me anytime I used a non-enhanced journal sheet for a journal entry. Maybe that's the problem you're running into.
 
Yup that is whats happening, default sheet was set to `Default Journal Entry Sheet` changing this to `Enhanced Journal Entry`... That fixed the issue, but if a sheet is set to anything other then that, it still crashes for me on version 1.0.44
