### ISSUE TITLE
Cannot open pre-existing journal entries from map or journal tab

### ISSUE THREAD

**Issue by MrVauxs** [ironmonk88/monks-enhanced-journal#20]
**Core Version:** 0.8.6
**System:** dnd5e 1.3.3 
**Module V.:** 1.0.29

The issue happens only when clicking dropped journal entries on the map or in the actual Journal Entry tab, than through the enhanced journal. It works in the latter.

![image](https://user-images.githubusercontent.com/32039708/120720865-1c798d80-c4cd-11eb-8f25-b02e4c99768b.png)

**Comment by amcvfx** [comment]
I'm not sure if this is the same issue I am having but when clicking on Journal Links within a journal entry it doesn't navigate to the link. This message pops up in the console:

![image](https://user-images.githubusercontent.com/35099081/120938926-386b7200-c70d-11eb-90e6-9ef65a82c1f7.png)

**Comment by ironmonk88** [comment]
Can you try it again with the latest version?  I think it may have been solved but I'm not sure.

**Comment by MrVauxs** [comment]
> Can you try it again with the latest version? I think it may have been solved but I'm not sure.

The journal opens as usual (vanilla) way. Albeit the console displays this error.
![image](https://user-images.githubusercontent.com/32039708/120969830-f113ce80-c76a-11eb-9b29-d2450321b2ec.png)

**Comment by ironmonk88** [comment]
What steps are you doing to get that error?

**Comment by MrVauxs** [comment]
> What steps are you doing to get that error?

Opening a journal entry (any, whether it is vanilla or a type from the module). The journal now opens (showing vanilla journal notes), but that error is still there.

**Comment by ironmonk88** [comment]
Lots of things have changed.  Is the error still there?

**Comment by MrVauxs** [comment]
No. The errors are gone now.
