### ISSUE TITLE
Losing data when journals enter compendiums

### ISSUE THREAD

**Issue by Nedrapter** [ironmonk88/monks-enhanced-journal#61]
I was very amazed with the layout and functionality of the module! Very good job! I started making journals for everything after seeing this module. For people, places, faction etc! However when I placed them into my shared compendium (cause I have many words), and then imported them into the worlds, they have lost their format and some data. For example, a person type journal reverted to normal journal, lost the info about race, profession, faction, and the linked actor (although it kept the linked actors in the description -both were coming from the same compendium). 
With that problem happening, all the reasons to make those awesome journals with the module become invalid, cause I need them shared through my compendiums.

I'm not sure if it's a bug or something intended though.

**Comment by ironmonk88** [comment]
It sounds like they're losing their flags.  That's where I store all the information.
I'll look into it.

**Comment by ironmonk88** [comment]
Yep.  It was losing flags when saving to the compendium and when importing them from the compendium.
I think that's an issue with Foundry.
It can save the flags, so there's no issue with them being them.  And it even saved the root of my flags.. but didn't save the actual data itself.
I overrode the function I could find and after it was finished exporting/importing I just saved the flags back in.
There's still some clean up left, but it should be fixed now.

**Comment by DanielTheBard** [comment]
Has this fix still not been released, or has a new issue(s) popped up with making it so? Because this remains a problem for me, and while I love the module, having the data get wiped out by importing from/exporting to a shared compendium, makes the module sadly much less useful for me.

**Comment by enigmafyv** [comment]
I was curious if this was already implemented?  I'm seeing the same behavior today and really enjoy using this mod.  I can reimport the shop data (in my case), but then I have to do that every time I pull the journal entry out of the compendium.   I see this is still "open" so I'm curious if this was ever pushed out?  I'm using the Earthdawn system, so I don't know if there's some incompatibility with it.  {shrugs}
Thanks for making such a nice mod.  Really appreciate your contribution.

**Comment by Wade0004** [comment]
I was noticing a little of the same, in that it was dropping all my "relationships" when I was saving to a compendium.  But not only was it not saving my "relationships" into the compendium, it was deleting them from the active journal entry in my sidebar.  
"Compendium Folders" was the culprit, they must use the same flag? https://foundryvtt.com/packages/compendium-folders
When I turned "Compendium Folders" off it worked fine, even with a shared journal. But I really enjoy the organization that the "Compendium Folders" gives to me, is there a similar feature I can enable somehow?  I've got like 100 roll tables I have sorted into folders :( 

As mentioned above, fully appreciative of such an AWESOME journaling tool that is CHANGING the way I use Foundry and I really love it.

**Comment by Wade0004** [comment]
Actually, I spoke too soon.  Even without the Compendium Folders module I still am losing relationships when I load things into compendium.

**Comment by bularzik** [comment]
Thanks for the report. Looking back through the issue thread, this looks like it was addressed in a fix documented there, before the v14 migration — compendium round-trip overrides re-apply MEJ flags/data. I checked the current code and the fix is still in place, so I believe this is resolved. Let me know if you're still seeing it on a recent version.
